In [20]:
import numpy as np
import os
import random

In [1]:
!pip install opencv-contrib-python==3.4.2.17
import cv2 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 30.6 MB 71 kB/s 
  Attempting uninstall: opencv-contrib-python
    Found existing installation: opencv-contrib-python 4.1.2.30
    Uninstalling opencv-contrib-python-4.1.2.30:
      Successfully uninstalled opencv-contrib-python-4.1.2.30


In [3]:
# Create SURF object. 
surf = cv2.xfeatures2d.SURF_create()

In [7]:
queryImage_path = "/content/Modelo.png"
trainImage_path = "/content/t1.png"

queryImage = cv2.imread(queryImage_path, cv2.IMREAD_COLOR)
trainImage = cv2.imread(trainImage_path, cv2.IMREAD_COLOR)

In [8]:
queryImage_keypoints = surf.detect(queryImage,None)
trainImage_keypoints = surf.detect(trainImage, None)

In [9]:
queryImage_keypoints, queryImage_descriptors = surf.compute(queryImage, queryImage_keypoints)
trainImage_keypoints, trainImage_descriptors = surf.compute(trainImage, trainImage_keypoints)

In [10]:
bf = cv2.BFMatcher(cv2.NORM_L2, crossCheck=True)
matches = bf.match(queryImage_descriptors, trainImage_descriptors)

In [41]:
print("Number of Keypoints in query Image: ", len(queryImage_keypoints))
print("Number of Keypoints in training Image: ", len(trainImage_keypoints))
print("Number of Matching Keypoints Between The Training and Query Images: ", len(matches))

Number of Keypoints in query Image:  1366
Number of Keypoints in training Image:  1404
Number of Matching Keypoints Between The Training and Query Images:  516


In [11]:
# get three random match indices which are not the same
match_index_a = random.randint(0, len(matches) - 1)
match_index_b = random.randint(0, len(matches) - 1)
match_index_c = random.randint(0, len(matches) - 1)

In [15]:
# get Keypoints from match indices
# queryImage- keypoints
queryImage_keypoint_a = queryImage_keypoints[matches[match_index_a].queryIdx]
queryImage_keypoint_b = queryImage_keypoints[matches[match_index_b].queryIdx]
queryImage_keypoint_c = queryImage_keypoints[matches[match_index_c].queryIdx]

# trainImage-keypoints
trainImage_keypoint_a = trainImage_keypoints[matches[match_index_a].trainIdx]
trainImage_keypoint_b = trainImage_keypoints[matches[match_index_b].trainIdx]
trainImage_keypoint_c = trainImage_keypoints[matches[match_index_c].trainIdx]

In [21]:
# get affine transformation matrix from these 6 keypoints
trainImage_points = np.float32([[trainImage_keypoint_a.pt[0], trainImage_keypoint_a.pt[1]],
                                [trainImage_keypoint_b.pt[0], trainImage_keypoint_b.pt[1]],
                                [trainImage_keypoint_c.pt[0], trainImage_keypoint_c.pt[1]]])

queryImage_points = np.float32([[queryImage_keypoint_a.pt[0], queryImage_keypoint_a.pt[1]],
                                [queryImage_keypoint_b.pt[0], queryImage_keypoint_b.pt[1]],
                                [queryImage_keypoint_c.pt[0], queryImage_keypoint_c.pt[1]]])


In [22]:
queryImage_points

array([[160.25482 , 238.13702 ],
       [329.6805  , 116.232376],
       [173.82631 , 146.08896 ]], dtype=float32)

In [23]:
trainImage_points

array([[299.58804 ,  59.626835],
       [139.36641 , 137.42348 ],
       [250.63588 ,  82.67121 ]], dtype=float32)

In [24]:
# get transformation matrix for current points
currentMatrix = cv2.getAffineTransform(queryImage_points, trainImage_points)

In [37]:
print('Affine transformation')
currentMatrix

Affine transformation


array([[-6.29845133e-01,  4.38947069e-01,  2.95994214e+02],
       [ 3.12162070e-01, -2.04326650e-01,  5.82590982e+01]])